name: tomas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.36+46

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_logging: any
  flutter_svg: ^1.1.6
  loading: ^1.0.2
  url_launcher: ^6.1.6
  dio: ^4.0.6
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  country_code_picker: ^2.0.2
  permission_handler: ^10.2.0
  jwt_decoder: ^2.0.1
  mapbox_gl: ^0.16.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  qr_flutter: ^4.0.0
  pull_to_refresh: ^2.0.0
  connectivity: ^3.0.6
  flutter_mapbox_navigation: ^0.0.26
  location_permissions: ^4.0.1
  mapbox_search: ^3.0.1+2
  flutter_map: ^3.0.0
  open_mail_app: ^0.4.5
  # device_preview: ^0.5.5
  toast: ^0.3.0
  package_info: ^2.0.2
  uni_links: ^0.5.1
  introduction_screen: ^3.0.2
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.5
  firebase_messaging: ^14.1.0
  firebase_database: ^10.0.5
  webview_flutter: ^3.0.4
  overlay_support: ^2.1.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.1
  latlng: any
  flutter_google_places: any
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.2.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locale/localization_en.json
    - assets/locale/localization_id.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
